blank_issues_enabled: false
contact_links:
  - name: Windows Q&A forums
    url: https://learn.microsoft.com/en-us/answers/tags/60/windows
    about: Find answers to your technical questions about Windows
